<a href="https://colab.research.google.com/github/achrisk/Dissertation/blob/main/Viewing_results.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/achrisk/Dissertation.git

Cloning into 'Dissertation'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 155 (delta 3), reused 0 (delta 0), pack-reused 142
Receiving objects: 100% (155/155), 226.90 MiB | 13.60 MiB/s, done.
Resolving deltas: 100% (65/65), done.
Checking out files: 100% (68/68), done.


In [16]:
import scipy.io as spio
from scipy import stats
import numpy as np
import pandas as pd
from importlib.machinery import SourceFileLoader
import pickle

# EEGNet-specific imports
from tensorflow.keras import utils as np_utils
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras import backend as K
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Activation, Permute, Dropout
from tensorflow.keras.layers import Conv2D, MaxPooling2D, AveragePooling2D
from tensorflow.keras.layers import SeparableConv2D, DepthwiseConv2D
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Input, Flatten
from tensorflow.keras.constraints import max_norm#
from google.colab import files
from sklearn.metrics import cohen_kappa_score
from google.colab import drive

K.set_image_data_format('channels_first')


from tensorflow.keras.regularizers import l1_l2

from tensorflow.keras.layers import SpatialDropout2D
K.set_image_data_format('channels_first')

from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression

# tools for plotting confusion matrices
from matplotlib import pyplot as plt
from scipy.signal import butter, lfilter

# formatting numbers
float_formatter = "{:.3f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})

In [37]:
model_name = 'DeepConvNet'  # ShallowConvNet or DeepConvNet
kernels, chans, samples = 1, 12, 1536
h_cut = [18,24,30]
drop_out = [0.25,0.5]
#k_len = [32,64,128,256]
n_epochs = 100


outfname_history = 'Dissertation/Results/DeepConvNet/Convolutional Layer_20/accuray_epochs' + str(n_epochs) + '_filter_' + str(h_cut) + '_drop_' + str(drop_out) + '_model_' + str(model_name) + '_history_data.pickle'
outfname = 'Dissertation/Results/DeepConvNet/Convolutional Layer_20/accuray_epochs' + str(n_epochs)  + '_filter_' + str(h_cut) + '_drop_' + str(drop_out) + '_model_' + str(model_name) + '_patient_data.pickle'

with open(outfname_history, 'rb') as handle:
    history = pickle.load(handle)

with open(outfname, 'rb') as handle:
    hyper_parameter_matrix = pickle.load(handle)

#mean across patients per given a selection of hyperparameters
hyper_parameter_matrix_mean_patient = np.mean(hyper_parameter_matrix, axis=0, keepdims=True) 

#standard error of mean across patients per given selection of hyperparameters
sem_acc = stats.sem(hyper_parameter_matrix, axis=0) #std across patients per given selection of hyperparameters
print(sem_acc)


[[[0.866 0.000 0.000 0.069]
  [0.866 0.000 0.000 0.068]]

 [[0.866 0.000 0.000 0.023]
  [0.866 0.000 0.000 0.044]]

 [[0.866 0.000 0.000 0.046]
  [0.866 0.000 0.000 0.076]]]


In [ ]:

ind = np.unravel_index(np.argmax(acc_sub, axis=None), acc_sub.shape) #index of optimal hyperparameters
acc_sub
hyper_parameter_matrix
hyper_parameter_matrix[ind] #accuracy of optimal model (i.e. best hyperparameters)
reduced_acc_sub = np.mean(acc_sub, axis=0, keepdims=True) #mean across patients per given selection of hyperparameters
hyper_parameter_matrix_sub = np.mean(hyper_parameter_matrix, axis=0, keepdims=True) #mean across patients per given selection of hyperparameters

sem_acc = np.std(acc_sub, axis=0, keepdims=True) #std across patients per given selection of hyperparameters

ind_reduced = np.unravel_index(np.argmax(reduced_acc_sub, axis=None), reduced_acc_sub.shape) #index for best hyperparameter selection for best mean accuracy across patients
#print('Index is: {}'.format(ind_reduced[-1]))
#print('Hyperparameters are: {}'.format(hyper_parameter_matrix[ind_reduced]))
#print(hyper_parameter_matrix[ind_reduced])

#print(acc_sub)



#print(reduced_acc_sub)
print(hyper_parameter_matrix_sub)
#print(sem_acc)